### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by merqurio** [kterf/ArduinoDroneProject#2]
Siempre he querido montarme un dron :grin: , a parte de arduino, que hardware usais??

**Comment by eduribas92** [comment]
Esta mañana estaba un poco espeso... mírate la wiki, concretamente: https://github.com/kterf/ArduinoDroneProject/wiki/Despeses
Ahí tenemos lo que ya hemos ido comprando para probar ;-)

**Comment by merqurio** [comment]
Hu! me hago con una de cada pero ya ! . Le comento a un colega, pero creo que va a ser proyecto de tiempo libre hahahaha

**Comment by eduribas92** [comment]
haha es cosa de ir haciendo! La programación es bastante fácil, el problema viene con la electrónica... hehe
